version: '3'

services:
  backend:
    build: ./back
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge